// initData.js

const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

async function main() {
  // Insertar datos iniciales para la tabla 'flags'
  await prisma.Flag.createMany({
    data: [
      { id: 1, name: "Afghanistan", flag: "🇦🇫" },
      { id: 2, name: "Aland Islands", flag: "🇦🇽" },
      { id: 3, name: "Albania", flag: "🇦🇱" },
      { id: 4, name: "Algeria", flag: "🇩🇿" },
      { id: 5, name: "American Samoa", flag: "🇦🇸" },
      { id: 6, name: "Andorra", flag: "🇦🇩" },
      { id: 7, name: "Angola", flag: "🇦🇴" },
      { id: 8, name: "Anguilla", flag: "🇦🇮" },
      { id: 9, name: "Antarctica", flag: "🇦🇶" },
      { id: 10, name: "Antigua And Barbuda", flag: "🇦🇬" },
      { id: 11, name: "Argentina", flag: "🇦🇷" },
      { id: 12, name: "Armenia", flag: "🇦🇲" },
      { id: 13, name: "Aruba", flag: "🇦🇼" },
      { id: 14, name: "Australia", flag: "🇦🇺" },
      { id: 15, name: "Austria", flag: "🇦🇹" },
      { id: 16, name: "Azerbaijan", flag: "🇦🇿" },
      { id: 18, name: "Bahrain", flag: "🇧🇭" },
      { id: 19, name: "Bangladesh", flag: "🇧🇩" },
      { id: 20, name: "Barbados", flag: "🇧🇧" },
      { id: 21, name: "Belarus", flag: "🇧🇾" },
      { id: 22, name: "Belgium", flag: "🇧🇪" },
      { id: 23, name: "Belize", flag: "🇧🇿" },
      { id: 24, name: "Benin", flag: "🇧🇯" },
      { id: 25, name: "Bermuda", flag: "🇧🇲" },
      { id: 26, name: "Bhutan", flag: "🇧🇹" },
      { id: 27, name: "Bolivia", flag: "🇧🇴" },
      { id: 155, name: "Bonaire, Sint Eustatius and Saba", flag: "🇧🇶" },
      { id: 28, name: "Bosnia and Herzegovina", flag: "🇧🇦" },
      { id: 29, name: "Botswana", flag: "🇧🇼" },
      { id: 30, name: "Bouvet Island", flag: "🇧🇻" },
      { id: 31, name: "Brazil", flag: "🇧🇷" },
      { id: 32, name: "British Indian Ocean Territory", flag: "🇮🇴" },
      { id: 33, name: "Brunei", flag: "🇧🇳" },
      { id: 34, name: "Bulgaria", flag: "🇧🇬" },
      { id: 35, name: "Burkina Faso", flag: "🇧🇫" },
      { id: 36, name: "Burundi", flag: "🇧🇮" },
      { id: 37, name: "Cambodia", flag: "🇰🇭" },
      { id: 38, name: "Cameroon", flag: "🇨🇲" },
      { id: 39, name: "Canada", flag: "🇨🇦" },
      { id: 40, name: "Cape Verde", flag: "🇨🇻" },
      { id: 41, name: "Cayman Islands", flag: "🇰🇾" },
      { id: 42, name: "Central African Republic", flag: "🇨🇫" },
      { id: 43, name: "Chad", flag: "🇹🇩" },
      { id: 44, name: "Chile", flag: "🇨🇱" },
      { id: 45, name: "China", flag: "🇨🇳" },
      { id: 46, name: "Christmas Island", flag: "🇨🇽" },
      { id: 47, name: "Cocos (Keeling) Islands", flag: "🇨🇨" },
      { id: 48, name: "Colombia", flag: "🇨🇴" },
      { id: 49, name: "Comoros", flag: "🇰🇲" },
      { id: 50, name: "Congo", flag: "🇨🇬" },
      { id: 52, name: "Cook Islands", flag: "🇨🇰" },
      { id: 53, name: "Costa Rica", flag: "🇨🇷" },
      { id: 54, name: "Cote D'Ivoire (Ivory Coast)", flag: "🇨🇮" },
      { id: 55, name: "Croatia", flag: "🇭🇷" },
      { id: 56, name: "Cuba", flag: "🇨🇺" },
      { id: 249, name: "Curaçao", flag: "🇨🇼" },
      { id: 57, name: "Cyprus", flag: "🇨🇾" },
      { id: 58, name: "Czech Republic", flag: "🇨🇿" },
      { id: 51, name: "Democratic Republic of the Congo", flag: "🇨🇩" },
      { id: 59, name: "Denmark", flag: "🇩🇰" },
      { id: 60, name: "Djibouti", flag: "🇩🇯" },
      { id: 61, name: "Dominica", flag: "🇩🇲" },
      { id: 62, name: "Dominican Republic", flag: "🇩🇴" },
      { id: 63, name: "East Timor", flag: "🇹🇱" },
      { id: 64, name: "Ecuador", flag: "🇪🇨" },
      { id: 65, name: "Egypt", flag: "🇪🇬" },
      { id: 66, name: "El Salvador", flag: "🇸🇻" },
      { id: 67, name: "Equatorial Guinea", flag: "🇬🇶" },
      { id: 68, name: "Eritrea", flag: "🇪🇷" },
      { id: 69, name: "Estonia", flag: "🇪🇪" },
      { id: 70, name: "Ethiopia", flag: "🇪🇹" },
      { id: 71, name: "Falkland Islands", flag: "🇫🇰" },
      { id: 72, name: "Faroe Islands", flag: "🇫🇴" },
      { id: 73, name: "Fiji Islands", flag: "🇫🇯" },
      { id: 74, name: "Finland", flag: "🇫🇮" },
      { id: 75, name: "France", flag: "🇫🇷" },
      { id: 76, name: "French Guiana", flag: "🇬🇫" },
      { id: 77, name: "French Polynesia", flag: "🇵🇫" },
      { id: 78, name: "French Southern Territories", flag: "🇹🇫" },
      { id: 79, name: "Gabon", flag: "🇬🇦" },
      { id: 80, name: "Gambia The", flag: "🇬🇲" },
      { id: 81, name: "Georgia", flag: "🇬🇪" },
      { id: 82, name: "Germany", flag: "🇩🇪" },
      { id: 83, name: "Ghana", flag: "🇬🇭" },
      { id: 84, name: "Gibraltar", flag: "🇬🇮" },
      { id: 85, name: "Greece", flag: "🇬🇷" },
      { id: 86, name: "Greenland", flag: "🇬🇱" },
      { id: 87, name: "Grenada", flag: "🇬🇩" },
      { id: 88, name: "Guadeloupe", flag: "🇬🇵" },
      { id: 89, name: "Guam", flag: "🇬🇺" },
      { id: 90, name: "Guatemala", flag: "🇬🇹" },
      { id: 91, name: "Guernsey and Alderney", flag: "🇬🇬" },
      { id: 92, name: "Guinea", flag: "🇬🇳" },
      { id: 93, name: "Guinea-Bissau", flag: "🇬🇼" },
      { id: 94, name: "Guyana", flag: "🇬🇾" },
      { id: 95, name: "Haiti", flag: "🇭🇹" },
      { id: 96, name: "Heard Island and McDonald Islands", flag: "🇭🇲" },
      { id: 97, name: "Honduras", flag: "🇭🇳" },
      { id: 98, name: "Hong Kong S.A.R.", flag: "🇭🇰" },
      { id: 99, name: "Hungary", flag: "🇭🇺" },
      { id: 100, name: "Iceland", flag: "🇮🇸" },
      { id: 101, name: "India", flag: "🇮🇳" },
      { id: 102, name: "Indonesia", flag: "🇮🇩" },
      { id: 103, name: "Iran", flag: "🇮🇷" },
      { id: 104, name: "Iraq", flag: "🇮🇶" },
      { id: 105, name: "Ireland", flag: "🇮🇪" },
      { id: 106, name: "Israel", flag: "🇮🇱" },
      { id: 107, name: "Italy", flag: "🇮🇹" },
      { id: 108, name: "Jamaica", flag: "🇯🇲" },
      { id: 109, name: "Japan", flag: "🇯🇵" },
      { id: 110, name: "Jersey", flag: "🇯🇪" },
      { id: 111, name: "Jordan", flag: "🇯🇴" },
      { id: 112, name: "Kazakhstan", flag: "🇰🇿" },
      { id: 113, name: "Kenya", flag: "🇰🇪" },
      { id: 114, name: "Kiribati", flag: "🇰🇮" },
      { id: 248, name: "Kosovo", flag: "🇽🇰" },
      { id: 117, name: "Kuwait", flag: "🇰🇼" },
      { id: 118, name: "Kyrgyzstan", flag: "🇰🇬" },
      { id: 119, name: "Laos", flag: "🇱🇦" },
      { id: 120, name: "Latvia", flag: "🇱🇻" },
      { id: 121, name: "Lebanon", flag: "🇱🇧" },
      { id: 122, name: "Lesotho", flag: "🇱🇸" },
      { id: 123, name: "Liberia", flag: "🇱🇷" },
      { id: 124, name: "Libya", flag: "🇱🇾" },
      { id: 125, name: "Liechtenstein", flag: "🇱🇮" },
      { id: 126, name: "Lithuania", flag: "🇱🇹" },
      { id: 127, name: "Luxembourg", flag: "🇱🇺" },
      { id: 128, name: "Macau S.A.R.", flag: "🇲🇴" },
      { id: 130, name: "Madagascar", flag: "🇲🇬" },
      { id: 131, name: "Malawi", flag: "🇲🇼" },
      { id: 132, name: "Malaysia", flag: "🇲🇾" },
      { id: 133, name: "Maldives", flag: "🇲🇻" },
      { id: 134, name: "Mali", flag: "🇲🇱" },
      { id: 135, name: "Malta", flag: "🇲🇹" },
      { id: 136, name: "Man (Isle of)", flag: "🇮🇲" },
      { id: 137, name: "Marshall Islands", flag: "🇲🇭" },
      { id: 138, name: "Martinique", flag: "🇲🇶" },
      { id: 139, name: "Mauritania", flag: "🇲🇷" },
      { id: 140, name: "Mauritius", flag: "🇲🇺" },
      { id: 141, name: "Mayotte", flag: "🇾🇹" },
      { id: 142, name: "Mexico", flag: "🇲🇽" },
      { id: 143, name: "Micronesia", flag: "🇫🇲" },
      { id: 144, name: "Moldova", flag: "🇲🇩" },
      { id: 145, name: "Monaco", flag: "🇲🇨" },
      { id: 146, name: "Mongolia", flag: "🇲🇳" },
      { id: 147, name: "Montenegro", flag: "🇲🇪" },
      { id: 148, name: "Montserrat", flag: "🇲🇸" },
      { id: 149, name: "Morocco", flag: "🇲🇦" },
      { id: 150, name: "Mozambique", flag: "🇲🇿" },
      { id: 151, name: "Myanmar", flag: "🇲🇲" },
      { id: 152, name: "Namibia", flag: "🇳🇦" },
      { id: 153, name: "Nauru", flag: "🇳🇷" },
      { id: 154, name: "Nepal", flag: "🇳🇵" },
      { id: 156, name: "Netherlands", flag: "🇳🇱" },
      { id: 157, name: "New Caledonia", flag: "🇳🇨" },
      { id: 158, name: "New Zealand", flag: "🇳🇿" },
      { id: 159, name: "Nicaragua", flag: "🇳🇮" },
      { id: 160, name: "Niger", flag: "🇳🇪" },
      { id: 161, name: "Nigeria", flag: "🇳🇬" },
      { id: 162, name: "Niue", flag: "🇳🇺" },
      { id: 163, name: "Norfolk Island", flag: "🇳🇫" },
      { id: 115, name: "North Korea", flag: "🇰🇵" },
      { id: 129, name: "North Macedonia", flag: "🇲🇰" },
      { id: 164, name: "Northern Mariana Islands", flag: "🇲🇵" },
      { id: 165, name: "Norway", flag: "🇳🇴" },
      { id: 166, name: "Oman", flag: "🇴🇲" },
      { id: 167, name: "Pakistan", flag: "🇵🇰" },
      { id: 168, name: "Palau", flag: "🇵🇼" },
      { id: 169, name: "Palestinian Territory Occupied", flag: "🇵🇸" },
      { id: 170, name: "Panama", flag: "🇵🇦" },
      { id: 171, name: "Papua new Guinea", flag: "🇵🇬" },
      { id: 172, name: "Paraguay", flag: "🇵🇾" },
      { id: 173, name: "Peru", flag: "🇵🇪" },
      { id: 174, name: "Philippines", flag: "🇵🇭" },
      { id: 175, name: "Pitcairn Island", flag: "🇵🇳" },
      { id: 176, name: "Poland", flag: "🇵🇱" },
      { id: 177, name: "Portugal", flag: "🇵🇹" },
      { id: 178, name: "Puerto Rico", flag: "🇵🇷" },
      { id: 179, name: "Qatar", flag: "🇶🇦" },
      { id: 180, name: "Reunion", flag: "🇷🇪" },
      { id: 181, name: "Romania", flag: "🇷🇴" },
      { id: 182, name: "Russia", flag: "🇷🇺" },
      { id: 183, name: "Rwanda", flag: "🇷🇼" },
      { id: 184, name: "Saint Helena", flag: "🇸🇭" },
      { id: 185, name: "Saint Kitts And Nevis", flag: "🇰🇳" },
      { id: 186, name: "Saint Lucia", flag: "🇱🇨" },
      { id: 187, name: "Saint Pierre and Miquelon", flag: "🇵🇲" },
      { id: 188, name: "Saint Vincent And The Grenadines", flag: "🇻🇨" },
      { id: 189, name: "Samoa", flag: "🇼🇸" },
      { id: 190, name: "San Marino", flag: "🇸🇲" },
      { id: 191, name: "Sao Tome and Principe", flag: "🇸🇹" },
      { id: 192, name: "Saudi Arabia", flag: "🇸🇦" },
      { id: 193, name: "Senegal", flag: "🇸🇳" },
      { id: 194, name: "Serbia", flag: "🇷🇸" },
      { id: 195, name: "Seychelles", flag: "🇸🇨" },
      { id: 196, name: "Sierra Leone", flag: "🇸🇱" },
      { id: 197, name: "Singapore", flag: "🇸🇬" },
      { id: 198, name: "Slovakia", flag: "🇸🇰" },
      { id: 199, name: "Slovenia", flag: "🇸🇮" },
      { id: 200, name: "Solomon Islands", flag: "🇸🇧" },
      { id: 201, name: "Somalia", flag: "🇸🇴" },
      { id: 202, name: "South Africa", flag: "🇿🇦" },
      { id: 203, name: "South Georgia", flag: "🇬🇸" },
      { id: 204, name: "South Korea", flag: "🇰🇷" },
      { id: 205, name: "South Sudan", flag: "🇸🇸" },
      { id: 206, name: "Spain", flag: "🇪🇸" },
      { id: 207, name: "Sri Lanka", flag: "🇱🇰" },
      { id: 208, name: "Sudan", flag: "🇸🇩" },
      { id: 209, name: "Suriname", flag: "🇸🇷" },
      { id: 210, name: "Svalbard And Jan Mayen Islands", flag: "🇸🇯" },
      { id: 211, name: "Swaziland", flag: "🇸🇿" },
      { id: 212, name: "Sweden", flag: "🇸🇪" },
      { id: 213, name: "Switzerland", flag: "🇨🇭" },
      { id: 214, name: "Syria", flag: "🇸🇾" },
      { id: 215, name: "Taiwan", flag: "🇹🇼" },
      { id: 216, name: "Tajikistan", flag: "🇹🇯" },
      { id: 217, name: "Tanzania", flag: "🇹🇿" },
      { id: 218, name: "Thailand", flag: "🇹🇭" },
      { id: 219, name: "Togo", flag: "🇹🇬" },
      { id: 220, name: "Tokelau", flag: "🇹🇰" },
      { id: 221, name: "Tonga", flag: "🇹🇴" },
      { id: 222, name: "Trinidad And Tobago", flag: "🇹🇹" },
      { id: 223, name: "Tunisia", flag: "🇹🇳" },
      { id: 224, name: "Turkey", flag: "🇹🇷" },
      { id: 225, name: "Turkmenistan", flag: "🇹🇲" },
      { id: 226, name: "Turks And Caicos Islands", flag: "🇹🇨" },
      { id: 227, name: "Tuvalu", flag: "🇹🇻" },
      { id: 228, name: "Uganda", flag: "🇺🇬" },
      { id: 229, name: "Ukraine", flag: "🇺🇦" },
      { id: 230, name: "United Arab Emirates", flag: "🇦🇪" },
      { id: 231, name: "United Kingdom", flag: "🇬🇧" },
      { id: 232, name: "United States", flag: "🇺🇸" },
      { id: 233, name: "United States Minor Outlying Islands", flag: "🇺🇲" },
      { id: 234, name: "Uruguay", flag: "🇺🇾" },
      { id: 235, name: "Uzbekistan", flag: "🇺🇿" },
      { id: 236, name: "Vanuatu", flag: "🇻🇺" },
      { id: 237, name: "Vatican City State (Holy See)", flag: "🇻🇦" },
      { id: 238, name: "Venezuela", flag: "🇻🇪" },
      { id: 239, name: "Vietnam", flag: "🇻🇳" },
      { id: 240, name: "Virgin Islands (British)", flag: "🇻🇬" },
      { id: 241, name: "Virgin Islands (US)", flag: "🇻🇮" },
      { id: 242, name: "Wallis And Futuna Islands", flag: "🇼🇫" },
      { id: 243, name: "Western Sahara", flag: "🇪🇭" },
      { id: 244, name: "Yemen", flag: "🇾🇪" },
      { id: 245, name: "Zambia", flag: "🇿🇲" },
      { id: 246, name: "Zimbabwe", flag: "🇿🇼" },
    ],
  });

  // Insertar datos iniciales para la tabla 'capitals'
  await prisma.Country.createMany({
    data: [
      { id: 1, country: "Afghanistan", capital: "Kabul" },
      { id: 2, country: "Aland Islands", capital: "Mariehamn" },
      { id: 3, country: "Albania", capital: "Tirana" },
      { id: 4, country: "Algeria", capital: "Algiers" },
      { id: 5, country: "American Samoa", capital: "Pago Pago" },
      { id: 6, country: "Andorra", capital: "Andorra la Vella" },
      { id: 7, country: "Angola", capital: "Luanda" },
      { id: 8, country: "Anguilla", capital: "The Valley" },
      { id: 9, country: "Antarctica", capital: null },
      { id: 10, country: "Antigua And Barbuda", capital: "St. John's" },
      { id: 11, country: "Argentina", capital: "Buenos Aires" },
      { id: 12, country: "Armenia", capital: "Yerevan" },
      { id: 13, country: "Aruba", capital: "Oranjestad" },
      { id: 14, country: "Australia", capital: "Canberra" },
      { id: 15, country: "Austria", capital: "Vienna" },
      { id: 16, country: "Azerbaijan", capital: "Baku" },
      { id: 17, country: "Bahrain", capital: "Manama" },
      { id: 18, country: "Bangladesh", capital: "Dhaka" },
      { id: 19, country: "Barbados", capital: "Bridgetown" },
      { id: 20, country: "Belarus", capital: "Minsk" },
      { id: 21, country: "Belgium", capital: "Brussels" },
      { id: 22, country: "Belize", capital: "Belmopan" },
      { id: 23, country: "Benin", capital: "Porto-Novo" },
      { id: 24, country: "Bermuda", capital: "Hamilton" },
      { id: 25, country: "Bhutan", capital: "Thimphu" },
      { id: 26, country: "Bolivia", capital: "Sucre" },
      {
        id: 27,
        country: "Bonaire, Sint Eustatius and Saba",
        capital: "Kralendijk",
      },
      { id: 28, country: "Bosnia and Herzegovina", capital: "Sarajevo" },
      { id: 29, country: "Botswana", capital: "Gaborone" },
      { id: 30, country: "Bouvet Island", capital: null },
      { id: 31, country: "Brazil", capital: "Brasilia" },
      {
        id: 32,
        country: "British Indian Ocean Territory",
        capital: "Diego Garcia",
      },
      { id: 33, country: "Brunei", capital: "Bandar Seri Begawan" },
      { id: 34, country: "Bulgaria", capital: "Sofia" },
      { id: 35, country: "Burkina Faso", capital: "Ouagadougou" },
      { id: 36, country: "Burundi", capital: "Bujumbura" },
      { id: 37, country: "Cambodia", capital: "Phnom Penh" },
      { id: 38, country: "Cameroon", capital: "Yaounde" },
      { id: 39, country: "Canada", capital: "Ottawa" },
      { id: 40, country: "Cape Verde", capital: "Praia" },
      { id: 41, country: "Cayman Islands", capital: "George Town" },
      { id: 42, country: "Central African Republic", capital: "Bangui" },
      { id: 43, country: "Chad", capital: "N'Djamena" },
      { id: 44, country: "Chile", capital: "Santiago" },
      { id: 45, country: "China", capital: "Beijing" },
      { id: 46, country: "Christmas Island", capital: "Flying Fish Cove" },
      { id: 47, country: "Cocos (Keeling) Islands", capital: "West Island" },
      { id: 48, country: "Colombia", capital: "Bogotá" },
      { id: 49, country: "Comoros", capital: "Moroni" },
      { id: 50, country: "Congo", capital: "Brazzaville" },
      { id: 51, country: "Cook Islands", capital: "Avarua" },
      { id: 52, country: "Costa Rica", capital: "San Jose" },
      {
        id: 53,
        country: "Cote D'Ivoire (Ivory Coast)",
        capital: "Yamoussoukro",
      },
      { id: 54, country: "Croatia", capital: "Zagreb" },
      { id: 55, country: "Cuba", capital: "Havana" },
      { id: 56, country: "Curaçao", capital: "Willemstad" },
      { id: 57, country: "Cyprus", capital: "Nicosia" },
      { id: 58, country: "Czech Republic", capital: "Prague" },
      {
        id: 59,
        country: "Democratic Republic of the Congo",
        capital: "Kinshasa",
      },
      { id: 60, country: "Denmark", capital: "Copenhagen" },
      { id: 61, country: "Djibouti", capital: "Djibouti" },
      { id: 62, country: "Dominica", capital: "Roseau" },
      { id: 63, country: "Dominican Republic", capital: "Santo Domingo" },
      { id: 64, country: "East Timor", capital: "Dili" },
      { id: 65, country: "Ecuador", capital: "Quito" },
      { id: 66, country: "Egypt", capital: "Cairo" },
      { id: 67, country: "El Salvador", capital: "San Salvador" },
      { id: 68, country: "Equatorial Guinea", capital: "Malabo" },
      { id: 69, country: "Eritrea", capital: "Asmara" },
      { id: 70, country: "Estonia", capital: "Tallinn" },
      { id: 71, country: "Ethiopia", capital: "Addis Ababa" },
      { id: 72, country: "Falkland Islands", capital: "Stanley" },
      { id: 73, country: "Faroe Islands", capital: "Torshavn" },
      { id: 74, country: "Fiji Islands", capital: "Suva" },
      { id: 75, country: "Finland", capital: "Helsinki" },
      { id: 76, country: "France", capital: "Paris" },
      { id: 77, country: "French Guiana", capital: "Cayenne" },
      { id: 78, country: "French Polynesia", capital: "Papeete" },
      {
        id: 79,
        country: "French Southern Territories",
        capital: "Port-aux-Francais",
      },
      { id: 80, country: "Gabon", capital: "Libreville" },
      { id: 81, country: "Gambia The", capital: "Banjul" },
      { id: 82, country: "Georgia", capital: "Tbilisi" },
      { id: 83, country: "Germany", capital: "Berlin" },
      { id: 84, country: "Ghana", capital: "Accra" },
      { id: 85, country: "Gibraltar", capital: "Gibraltar" },
      { id: 86, country: "Greece", capital: "Athens" },
      { id: 87, country: "Greenland", capital: "Nuuk" },
      { id: 88, country: "Grenada", capital: "St. George's" },
      { id: 89, country: "Guadeloupe", capital: "Basse-Terre" },
      { id: 90, country: "Guam", capital: "Hagatna" },
      { id: 91, country: "Guatemala", capital: "Guatemala City" },
      { id: 92, country: "Guernsey and Alderney", capital: "St Peter Port" },
      { id: 93, country: "Guinea", capital: "Conakry" },
      { id: 94, country: "Guinea-Bissau", capital: "Bissau" },
      { id: 95, country: "Guyana", capital: "Georgetown" },
      { id: 96, country: "Haiti", capital: "Port-au-Prince" },
      { id: 97, country: "Heard Island and McDonald Islands", capital: null },
      { id: 98, country: "Honduras", capital: "Tegucigalpa" },
      { id: 99, country: "Hong Kong S.A.R.", capital: "Hong Kong" },
      { id: 100, country: "Hungary", capital: "Budapest" },
      { id: 101, country: "Iceland", capital: "Reykjavik" },
      { id: 102, country: "India", capital: "New Delhi" },
      { id: 103, country: "Indonesia", capital: "Jakarta" },
      { id: 104, country: "Iran", capital: "Tehran" },
      { id: 105, country: "Iraq", capital: "Baghdad" },
      { id: 106, country: "Ireland", capital: "Dublin" },
      { id: 107, country: "Israel", capital: "Jerusalem" },
      { id: 108, country: "Italy", capital: "Rome" },
      { id: 109, country: "Jamaica", capital: "Kingston" },
      { id: 110, country: "Japan", capital: "Tokyo" },
      { id: 111, country: "Jersey", capital: "Saint Helier" },
      { id: 112, country: "Jordan", capital: "Amman" },
      { id: 113, country: "Kazakhstan", capital: "Astana" },
      { id: 114, country: "Kenya", capital: "Nairobi" },
      { id: 115, country: "Kiribati", capital: "Tarawa" },
      { id: 116, country: "Kosovo", capital: "Pristina" },
      { id: 117, country: "Kuwait", capital: "Kuwait City" },
      { id: 118, country: "Kyrgyzstan", capital: "Bishkek" },
      { id: 119, country: "Laos", capital: "Vientiane" },
      { id: 120, country: "Latvia", capital: "Riga" },
      { id: 121, country: "Lebanon", capital: "Beirut" },
      { id: 122, country: "Lesotho", capital: "Maseru" },
      { id: 123, country: "Liberia", capital: "Monrovia" },
      { id: 124, country: "Libya", capital: "Tripolis" },
      { id: 125, country: "Liechtenstein", capital: "Vaduz" },
      { id: 126, country: "Lithuania", capital: "Vilnius" },
      { id: 127, country: "Luxembourg", capital: "Luxembourg" },
      { id: 128, country: "Macau S.A.R.", capital: "Macao" },
      { id: 129, country: "Madagascar", capital: "Antananarivo" },
      { id: 130, country: "Malawi", capital: "Lilongwe" },
      { id: 131, country: "Malaysia", capital: "Kuala Lumpur" },
      { id: 132, country: "Maldives", capital: "Male" },
      { id: 133, country: "Mali", capital: "Bamako" },
      { id: 134, country: "Malta", capital: "Valletta" },
      { id: 135, country: "Man (Isle of)", capital: "Douglas, Isle of Man" },
      { id: 136, country: "Marshall Islands", capital: "Majuro" },
      { id: 137, country: "Martinique", capital: "Fort-de-France" },
      { id: 138, country: "Mauritania", capital: "Nouakchott" },
      { id: 139, country: "Mauritius", capital: "Port Louis" },
      { id: 140, country: "Mayotte", capital: "Mamoudzou" },
      { id: 141, country: "Mexico", capital: "Ciudad de México" },
      { id: 142, country: "Micronesia", capital: "Palikir" },
      { id: 143, country: "Moldova", capital: "Chisinau" },
      { id: 144, country: "Monaco", capital: "Monaco" },
      { id: 145, country: "Mongolia", capital: "Ulan Bator" },
      { id: 146, country: "Montenegro", capital: "Podgorica" },
      { id: 147, country: "Montserrat", capital: "Plymouth" },
      { id: 148, country: "Morocco", capital: "Rabat" },
      { id: 149, country: "Mozambique", capital: "Maputo" },
      { id: 150, country: "Myanmar", capital: "Nay Pyi Taw" },
      { id: 151, country: "Namibia", capital: "Windhoek" },
      { id: 152, country: "Nauru", capital: "Yaren" },
      { id: 153, country: "Nepal", capital: "Kathmandu" },
      { id: 154, country: "Netherlands", capital: "Amsterdam" },
      { id: 155, country: "New Caledonia", capital: "Noumea" },
      { id: 156, country: "New Zealand", capital: "Wellington" },
      { id: 157, country: "Nicaragua", capital: "Managua" },
      { id: 158, country: "Niger", capital: "Niamey" },
      { id: 159, country: "Nigeria", capital: "Abuja" },
      { id: 160, country: "Niue", capital: "Alofi" },
      { id: 161, country: "Norfolk Island", capital: "Kingston" },
      { id: 162, country: "North Korea", capital: "Pyongyang" },
      { id: 163, country: "North Macedonia", capital: "Skopje" },
      { id: 164, country: "Northern Mariana Islands", capital: "Saipan" },
      { id: 165, country: "Norway", capital: "Oslo" },
      { id: 166, country: "Oman", capital: "Muscat" },
      { id: 167, country: "Pakistan", capital: "Islamabad" },
      { id: 168, country: "Palau", capital: "Melekeok" },
      {
        id: 169,
        country: "Palestinian Territory Occupied",
        capital: "East Jerusalem",
      },
      { id: 170, country: "Panama", capital: "Panama City" },
      { id: 171, country: "Papua new Guinea", capital: "Port Moresby" },
      { id: 172, country: "Paraguay", capital: "Asuncion" },
      { id: 173, country: "Peru", capital: "Lima" },
      { id: 174, country: "Philippines", capital: "Manila" },
      { id: 175, country: "Pitcairn Island", capital: "Adamstown" },
      { id: 176, country: "Poland", capital: "Warsaw" },
      { id: 177, country: "Portugal", capital: "Lisbon" },
      { id: 178, country: "Puerto Rico", capital: "San Juan" },
      { id: 179, country: "Qatar", capital: "Doha" },
      { id: 180, country: "Reunion", capital: "Saint-Denis" },
      { id: 181, country: "Romania", capital: "Bucharest" },
      { id: 182, country: "Russia", capital: "Moscow" },
      { id: 183, country: "Rwanda", capital: "Kigali" },
      { id: 184, country: "Saint Helena", capital: "Jamestown" },
      { id: 185, country: "Saint Kitts And Nevis", capital: "Basseterre" },
      { id: 186, country: "Saint Lucia", capital: "Castries" },
      {
        id: 187,
        country: "Saint Pierre and Miquelon",
        capital: "Saint-Pierre",
      },
      {
        id: 188,
        country: "Saint Vincent And The Grenadines",
        capital: "Kingstown",
      },
      { id: 189, country: "Saint-Barthelemy", capital: "Gustavia" },
      { id: 190, country: "Saint-Martin (French part)", capital: "Marigot" },
      { id: 191, country: "Samoa", capital: "Apia" },
      { id: 192, country: "San Marino", capital: "San Marino" },
      { id: 193, country: "Sao Tome and Principe", capital: "Sao Tome" },
      { id: 194, country: "Saudi Arabia", capital: "Riyadh" },
      { id: 195, country: "Senegal", capital: "Dakar" },
      { id: 196, country: "Serbia", capital: "Belgrade" },
      { id: 197, country: "Seychelles", capital: "Victoria" },
      { id: 198, country: "Sierra Leone", capital: "Freetown" },
      { id: 199, country: "Singapore", capital: "Singapur" },
      {
        id: 200,
        country: "Sint Maarten (Dutch part)",
        capital: "Philipsburg",
      },
      { id: 201, country: "Slovakia", capital: "Bratislava" },
      { id: 202, country: "Slovenia", capital: "Ljubljana" },
      { id: 203, country: "Solomon Islands", capital: "Honiara" },
      { id: 204, country: "Somalia", capital: "Mogadishu" },
      { id: 205, country: "South Africa", capital: "Pretoria" },
      { id: 206, country: "South Georgia", capital: "Grytviken" },
      { id: 207, country: "South Korea", capital: "Seoul" },
      { id: 208, country: "South Sudan", capital: "Juba" },
      { id: 209, country: "Spain", capital: "Madrid" },
      { id: 210, country: "Sri Lanka", capital: "Colombo" },
      { id: 211, country: "Sudan", capital: "Khartoum" },
      { id: 212, country: "Suriname", capital: "Paramaribo" },
      {
        id: 213,
        country: "Svalbard And Jan Mayen Islands",
        capital: "Longyearbyen",
      },
      { id: 214, country: "Swaziland", capital: "Mbabane" },
      { id: 215, country: "Sweden", capital: "Stockholm" },
      { id: 216, country: "Switzerland", capital: "Bern" },
      { id: 217, country: "Syria", capital: "Damascus" },
      { id: 218, country: "Taiwan", capital: "Taipei" },
      { id: 219, country: "Tajikistan", capital: "Dushanbe" },
      { id: 220, country: "Tanzania", capital: "Dodoma" },
      { id: 221, country: "Thailand", capital: "Bangkok" },
      { id: 222, country: "The Bahamas", capital: "Nassau" },
      { id: 223, country: "Togo", capital: "Lome" },
      { id: 224, country: "Tokelau", capital: null },
      { id: 225, country: "Tonga", capital: "Nuku'alofa" },
      { id: 226, country: "Trinidad And Tobago", capital: "Port of Spain" },
      { id: 227, country: "Tunisia", capital: "Tunis" },
      { id: 228, country: "Turkey", capital: "Ankara" },
      { id: 229, country: "Turkmenistan", capital: "Ashgabat" },
      {
        id: 230,
        country: "Turks And Caicos Islands",
        capital: "Cockburn Town",
      },
      { id: 231, country: "Tuvalu", capital: "Funafuti" },
      { id: 232, country: "Uganda", capital: "Kampala" },
      { id: 233, country: "Ukraine", capital: "Kyiv" },
      { id: 234, country: "United Arab Emirates", capital: "Abu Dhabi" },
      { id: 235, country: "United Kingdom", capital: "London" },
      { id: 236, country: "United States", capital: "Washington" },
      {
        id: 237,
        country: "United States Minor Outlying Islands",
        capital: null,
      },
      { id: 238, country: "Uruguay", capital: "Montevideo" },
      { id: 239, country: "Uzbekistan", capital: "Tashkent" },
      { id: 240, country: "Vanuatu", capital: "Port Vila" },
      {
        id: 241,
        country: "Vatican City State (Holy See)",
        capital: "Vatican City",
      },
      { id: 242, country: "Venezuela", capital: "Caracas" },
      { id: 243, country: "Vietnam", capital: "Hanoi" },
      { id: 244, country: "Virgin Islands (British)", capital: "Road Town" },
      {
        id: 245,
        country: "Virgin Islands (US)",
        capital: "Charlotte Amalie",
      },
      { id: 246, country: "Wallis And Futuna Islands", capital: "Mata Utu" },
      { id: 247, country: "Western Sahara", capital: "El-Aaiun" },
      { id: 248, country: "Yemen", capital: "Sanaa" },
      { id: 249, country: "Zambia", capital: "Lusaka" },
      { id: 250, country: "Zimbabwe", capital: "Harare" },
    ],
  });
}

main()
  .catch((e) => {
    throw e;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
